# Translations template for glance.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the glance project.
#
# Translators:
# HyunWoo Jo <showaid@gmail.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: Glance\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-04-03 06:02+0000\n"
"PO-Revision-Date: 2015-04-01 21:54+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Korean (Korea) (http://www.transifex.com/projects/p/glance/"
"language/ko_KR/)\n"
"Language: ko_KR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: glance/listener.py:40
#, python-format
msgid ""
"Failed to retrieve supported notification events from search plugins "
"%(ext)s: %(e)s"
msgstr ""

#: glance/location.py:403
#, python-format
msgid ""
"Glance tried all active locations to get data for image %s but all have "
"failed."
msgstr ""
"Glance는 모든 활성화 된 위치에서 %s 이미지에 대한 데이터를 수집하려 했으나 모"
"두 실패했습니다."

#: glance/notifier.py:361 glance/api/common.py:95
#, python-format
msgid "An error occurred during image.send notification: %(err)s"
msgstr "image.send notification 중 에러 발생 : %(err)s"

#: glance/scrubber.py:168
#, python-format
msgid "%s file can not be read."
msgstr "%s 파일을 읽을 수 없습니다."

#: glance/scrubber.py:191
#, python-format
msgid "%s file can not be wrote."
msgstr "%s 파일에 쓸 수 없습니다."

#: glance/scrubber.py:517
#, python-format
msgid "Can not %(op)s scrub jobs from queue: %(err)s"
msgstr "큐에 있는 %(op)s 스크럽 작업을 수행할 수 없음: %(err)s"

#: glance/scrubber.py:618
#, python-format
msgid "%s file can not be created."
msgstr "%s 파일을 만들 수 없습니다."

#: glance/api/common.py:58
#, python-format
msgid ""
"An error occurred reading from backend storage for image %(image_id)s: "
"%(err)s"
msgstr "백엔드 스토리지에서 이미지 %(image_id)s를 읽는 중 에러 발생: %(err)s"

#: glance/api/common.py:64
#, python-format
msgid ""
"Backend storage for image %(image_id)s disconnected after writing only "
"%(bytes_written)d bytes"
msgstr ""
"백엔드 스토리지에 이미지 %(image_id)s 를 %(bytes_written)d byte 를 쓰는 도중 "
"연결 끊김"

#: glance/api/common.py:123
#, python-format
msgid "Invalid value for option user_storage_quota: %(users_quota)s"
msgstr ""

#: glance/api/middleware/cache.py:173
#, python-format
msgid ""
"Image cache contained image file for image '%s', however the registry did "
"not contain metadata for that image!"
msgstr ""
"이미지 캐시에는 이미지 '%s'에 대한 이미지 파일이 있으나 레지스트리는 이미지"
"에 대한 메타데이터를 가지고 있지 않습니다!"

#: glance/api/middleware/cache.py:272
#, python-format
msgid "could not find %s"
msgstr "%s 를 찾을 수 없음"

#: glance/api/middleware/cache.py:291
msgid "Checksum header is missing."
msgstr "Checksum header 없음"

#: glance/api/v1/images.py:603
#, python-format
msgid "Copy from external source '%(scheme)s' failed for image: %(image)s"
msgstr "외부 소스 '%(scheme)s' 로부터 이미지 복사 실패 : %(image)s"

#: glance/api/v1/upload_utils.py:79
#, python-format
msgid "Unable to kill image %(id)s: "
msgstr "이미지 %(id)s 를 kill 할 수 없음:"

#: glance/api/v1/upload_utils.py:266
#, python-format
msgid "Received HTTP error while uploading image %s"
msgstr "이미지 %s를 업로드 하는 도중 HTTP 에러 수신"

#: glance/api/v2/image_data.py:60
#, python-format
msgid "Unable to restore image %(image_id)s: %(e)s"
msgstr "이미지 %(image_id)s를 복구할 수 없음 : %(e)s"

#: glance/api/v2/image_data.py:155 glance/api/v2/image_data.py:159
msgid "Failed to upload image data due to HTTP error"
msgstr "HTTP 에러로 인해 이미지 데이터 업로드 실패"

#: glance/api/v2/image_data.py:164
msgid "Failed to upload image data due to internal error"
msgstr "내부 에러로 인해 이미지 데이터 업로드 실패"

#: glance/api/v2/metadef_namespaces.py:207
#, python-format
msgid "Failed to delete namespace %(namespace)s "
msgstr "네임스페이스 삭제 실패 %(namespace)s"

#: glance/async/__init__.py:68
msgid ""
"This execution of Tasks is not setup. Please consult the project "
"documentation for more information on the executors available."
msgstr ""
"이 작업의 실행은 설정되지 않았습니다. 프로젝트 문서의 executors available 관"
"련 항목을 참고하여 상세한 정보를 확인 하시기 바랍니다."

#: glance/async/__init__.py:72
msgid "Internal error occurred while trying to process task."
msgstr "작업을 수행하는 중 내부에러 발생"

#: glance/async/taskflow_executor.py:130
#, python-format
msgid "Failed to execute task %(task_id)s: %(exc)s"
msgstr ""

#: glance/async/flows/base_import.py:341
#, python-format
msgid "Task ID %s"
msgstr ""

#: glance/async/flows/introspect.py:60
#, python-format
msgid "Failed to execute introspection %(task_id)s: %(exc)s"
msgstr ""

#: glance/cmd/index.py:48
#, python-format
msgid "Failed to setup index extension %(ext)s: %(e)s"
msgstr ""

#: glance/common/property_utils.py:84
#, python-format
msgid "Couldn't find property protection file %(file)s: %(error)s."
msgstr ""

#: glance/common/property_utils.py:91
#, python-format
msgid ""
"Invalid value '%s' for 'property_protection_rule_format'. The permitted "
"values are 'roles' and 'policies'"
msgstr ""

#: glance/common/property_utils.py:110
#, python-format
msgid ""
"Multiple policies '%s' not allowed for a given operation. Policies can be "
"combined in the policy file"
msgstr ""

#: glance/common/property_utils.py:123
#, python-format
msgid ""
"Malformed property protection rule in [%(prop)s] %(op)s=%(perm)s: '@' and "
"'!' are mutually exclusive"
msgstr ""

#: glance/common/property_utils.py:148
#, python-format
msgid "Encountered a malformed property protection rule %(rule)s: %(error)s."
msgstr ""

#: glance/common/rpc.py:186
#, python-format
msgid ""
"RPC Call Error: %(val)s\n"
"%(tb)s"
msgstr ""

#: glance/common/store_utils.py:71
#, python-format
msgid "Failed to delete image %(image_id)s from store: %(exc)s"
msgstr "스토어에서 이미지 %(image_id)s 삭제 실패 : %(exc)s"

#: glance/common/swift_store_utils.py:87
#, python-format
msgid "swift config file %(conf_file)s:%(exc)s not found"
msgstr ""

#: glance/common/swift_store_utils.py:101
msgid "Invalid format of swift store config cfg"
msgstr ""

#: glance/common/utils.py:115
#, python-format
msgid "Error: cooperative_iter exception %s"
msgstr ""

#: glance/common/utils.py:514
msgid ""
"Error setting up the debug environment. Verify that the option "
"pydev_worker_debug_host is pointing to a valid hostname or IP on which a "
"pydev server is listening on the port indicated by pydev_worker_debug_port."
msgstr ""

#: glance/common/wsgi.py:332
#, python-format
msgid "Not respawning child %d, cannot recover from termination"
msgstr ""

#: glance/common/artifacts/loader.py:96
#, python-format
msgid "Unable to load artifacts: %s"
msgstr ""

#: glance/common/artifacts/loader.py:164
#, python-format
msgid "Could not load plugin from %(module)s: %(msg)s"
msgstr ""

#: glance/common/location_strategy/__init__.py:66
#, python-format
msgid "Failed to load location strategy module %(module)s: %(e)s"
msgstr ""

#: glance/common/scripts/__init__.py:40
#, python-format
msgid ""
"This task type %(task_type)s is not supported by the current deployment of "
"Glance. Please refer the documentation provided by OpenStack or your "
"operator for more information."
msgstr ""
"이 작업 유형 %(task_type)s는 현재 배포된 Glance에서 지원되지 않습니다. 상세 "
"정보는 오픈스택이나 운영자로부터 배포된 문서를 참조바랍니다."

#: glance/common/scripts/__init__.py:50
#, python-format
msgid "Failed to save task %(task_id)s in DB as task_repo is %(task_repo)s"
msgstr ""
"DB에 task_repo 형태로 작업 %(task_id)s 저장에 실패한 것은 %(task_repo)s"

#: glance/common/scripts/utils.py:48
#, python-format
msgid "Task not found for task_id %s"
msgstr "task_id %s에 대한 작업을 찾을 수 없음"

#: glance/db/sqlalchemy/artifacts.py:346
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "알 수 없는 정렬 방향입니다. 'desc' 또는 'asc'여야 함"

#: glance/db/sqlalchemy/artifacts.py:532
msgid "Cannot use this parameter with the operator IN"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:539
#, python-format
msgid "Operator %s is not supported"
msgstr ""

#: glance/db/sqlalchemy/metadata.py:185
#, python-format
msgid "Json schema files not found in %s. Aborting."
msgstr "%s에서 Json 스키마 파일을 찾을 수 없음. 중단."

#: glance/db/sqlalchemy/metadata.py:451
msgid ""
"To use --prefer_new or --overwrite you need to combine of these options with "
"--merge option."
msgstr ""

#: glance/db/sqlalchemy/metadata.py:456
msgid ""
"Please provide no more than one option from this list: --prefer_new, --"
"overwrite"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:63
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:97
#, python-format
msgid "Invalid store uri for image: %(image_id)s. Details: %(reason)s"
msgstr "이미지 %(image_id)s 에 부적합한 저장 uri. 상세: %(reason)s"

#: glance/domain/__init__.py:413
#, python-format
msgid ""
"Task [%(task_id)s] status failed to change from %(cur_status)s to "
"%(new_status)s"
msgstr ""

#: glance/domain/__init__.py:521
#, python-format
msgid "Failed to load the %s executor provided in the config."
msgstr "설정에서 제공된 %s executor 로드 실패"

#: glance/image_cache/__init__.py:271
#, python-format
msgid ""
"Exception encountered while tee'ing image '%(image_id)s' into cache: "
"%(error)s. Continuing with response."
msgstr ""
"이미지 '%(image_id)s'를 캐시에 올리는 중 Exception 발생: %(error)s. 응답과 함"
"께 진행"

#: glance/image_cache/drivers/sqlite.py:398
#, python-format
msgid "Error executing SQLite call. Got error: %s"
msgstr "SQLLite call 수행중 에러 발생 : %s"

#: glance/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "고정 기간 루프 호출에서"

#: glance/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "동적 루프 호출에서"

#: glance/openstack/common/service.py:264
msgid "Unhandled exception"
msgstr "처리되지 않은 예외"

#: glance/registry/api/v1/images.py:136
msgid "Unable to get images"
msgstr "이미지를 가져올 수 없음"

#: glance/registry/api/v1/images.py:354
#, python-format
msgid "Unable to show image %s"
msgstr "이미지 %s를 보여줄 수 없음"

#: glance/registry/api/v1/images.py:390
#, python-format
msgid "Unable to delete image %s"
msgstr "이미지 %s를 삭제할 수 없음"

#: glance/registry/api/v1/images.py:442
#, python-format
msgid "Unable to create image %s"
msgstr "이미지 %s를 생성할 수 없음"

#: glance/registry/api/v1/images.py:515
#, python-format
msgid "Unable to update image %s"
msgstr "이미지 %s를 업데이트 할 수 없음"

#: glance/registry/client/v1/client.py:129
#, python-format
msgid "Registry client request %(method)s %(action)s raised %(exc_name)s"
msgstr ""

#: glance/search/api/v0_1/search.py:243
#, python-format
msgid "Failed to retrieve RBAC filters from search plugin %(ext)s: %(e)s"
msgstr ""

#: glance/tests/functional/v2/test_metadef_resourcetypes.py:99
#, python-format
msgid "Forbidden to create resource type. Reason: %(reason)s"
msgstr "리소스타입 생성이 금지됨. 이유: %(reason)s"
