# Translations template for glance.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the glance project.
#
# Translators:
# Maxime COQUEREL <max.coquerel@gmail.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: Glance\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-04-03 06:02+0000\n"
"PO-Revision-Date: 2015-04-01 21:54+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: French (http://www.transifex.com/projects/p/glance/language/"
"fr/)\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: glance/listener.py:40
#, python-format
msgid ""
"Failed to retrieve supported notification events from search plugins "
"%(ext)s: %(e)s"
msgstr ""

#: glance/location.py:403
#, python-format
msgid ""
"Glance tried all active locations to get data for image %s but all have "
"failed."
msgstr ""

#: glance/notifier.py:361 glance/api/common.py:95
#, python-format
msgid "An error occurred during image.send notification: %(err)s"
msgstr "Une erreur s'est produite lors de la notification image.send : %(err)s"

#: glance/scrubber.py:168
#, python-format
msgid "%s file can not be read."
msgstr "Le fichier %s ne peut pas etre lu."

#: glance/scrubber.py:191
#, python-format
msgid "%s file can not be wrote."
msgstr "Le fichier %s ne peut pas etre écrit."

#: glance/scrubber.py:517
#, python-format
msgid "Can not %(op)s scrub jobs from queue: %(err)s"
msgstr ""

#: glance/scrubber.py:618
#, python-format
msgid "%s file can not be created."
msgstr "Le fichier %s ne peut pas etre créé"

#: glance/api/common.py:58
#, python-format
msgid ""
"An error occurred reading from backend storage for image %(image_id)s: "
"%(err)s"
msgstr ""
"Une erreur s'est produite pendant le stockage backend de l'image "
"%(image_id)s : %(err)s "

#: glance/api/common.py:64
#, python-format
msgid ""
"Backend storage for image %(image_id)s disconnected after writing only "
"%(bytes_written)d bytes"
msgstr ""
"Le stockage d'arrière plan pour l'image %(image_id)s s'est déconnecté après "
"l'écriture de seulement %(bytes_written)d octets "

#: glance/api/common.py:123
#, python-format
msgid "Invalid value for option user_storage_quota: %(users_quota)s"
msgstr "Valeur invalide pour l'option user_storage_quota: %(users_quota)s"

#: glance/api/middleware/cache.py:173
#, python-format
msgid ""
"Image cache contained image file for image '%s', however the registry did "
"not contain metadata for that image!"
msgstr ""
"Le cache d'image contenait un fichier image pour l'image '%s', néanmoins le "
"registre ne contenait pas de métadonnées pour cette image ! "

#: glance/api/middleware/cache.py:272
#, python-format
msgid "could not find %s"
msgstr "impossible de trouver %s"

#: glance/api/middleware/cache.py:291
msgid "Checksum header is missing."
msgstr "L'en-tête de total de contrôle est manquant."

#: glance/api/v1/images.py:603
#, python-format
msgid "Copy from external source '%(scheme)s' failed for image: %(image)s"
msgstr ""
"Echec de copie depuis la source externe '%(scheme)s' pour l'image: %(image)s"

#: glance/api/v1/upload_utils.py:79
#, python-format
msgid "Unable to kill image %(id)s: "
msgstr "Impossible de supprimer l'image %(id)s :"

#: glance/api/v1/upload_utils.py:266
#, python-format
msgid "Received HTTP error while uploading image %s"
msgstr "Une erreur HTTP a été reçu lors du chargement de l'image %s"

#: glance/api/v2/image_data.py:60
#, python-format
msgid "Unable to restore image %(image_id)s: %(e)s"
msgstr "Impossible de restaurer l'image %(image_id)s: %(e)s"

#: glance/api/v2/image_data.py:155 glance/api/v2/image_data.py:159
msgid "Failed to upload image data due to HTTP error"
msgstr ""
"Echec de téléchargement des données de l'image en raison d'une erreur HTTP"

#: glance/api/v2/image_data.py:164
msgid "Failed to upload image data due to internal error"
msgstr ""
"Echec de téléchargement des données de l'image en raison d'une erreur interne"

#: glance/api/v2/metadef_namespaces.py:207
#, python-format
msgid "Failed to delete namespace %(namespace)s "
msgstr "Echec lors de la suppresion du namespace %(namespace)s"

#: glance/async/__init__.py:68
msgid ""
"This execution of Tasks is not setup. Please consult the project "
"documentation for more information on the executors available."
msgstr ""

#: glance/async/__init__.py:72
msgid "Internal error occurred while trying to process task."
msgstr "Erreur interne s'est produite lors du traitement de la tâche ."

#: glance/async/taskflow_executor.py:130
#, python-format
msgid "Failed to execute task %(task_id)s: %(exc)s"
msgstr ""

#: glance/async/flows/base_import.py:341
#, python-format
msgid "Task ID %s"
msgstr ""

#: glance/async/flows/introspect.py:60
#, python-format
msgid "Failed to execute introspection %(task_id)s: %(exc)s"
msgstr ""

#: glance/cmd/index.py:48
#, python-format
msgid "Failed to setup index extension %(ext)s: %(e)s"
msgstr ""

#: glance/common/property_utils.py:84
#, python-format
msgid "Couldn't find property protection file %(file)s: %(error)s."
msgstr ""

#: glance/common/property_utils.py:91
#, python-format
msgid ""
"Invalid value '%s' for 'property_protection_rule_format'. The permitted "
"values are 'roles' and 'policies'"
msgstr ""

#: glance/common/property_utils.py:110
#, python-format
msgid ""
"Multiple policies '%s' not allowed for a given operation. Policies can be "
"combined in the policy file"
msgstr ""

#: glance/common/property_utils.py:123
#, python-format
msgid ""
"Malformed property protection rule in [%(prop)s] %(op)s=%(perm)s: '@' and "
"'!' are mutually exclusive"
msgstr ""

#: glance/common/property_utils.py:148
#, python-format
msgid "Encountered a malformed property protection rule %(rule)s: %(error)s."
msgstr ""

#: glance/common/rpc.py:186
#, python-format
msgid ""
"RPC Call Error: %(val)s\n"
"%(tb)s"
msgstr ""

#: glance/common/store_utils.py:71
#, python-format
msgid "Failed to delete image %(image_id)s from store: %(exc)s"
msgstr "Echec de supprésion de l'image %(image_id)s depuis le magasin: %(exc)s"

#: glance/common/swift_store_utils.py:87
#, python-format
msgid "swift config file %(conf_file)s:%(exc)s not found"
msgstr ""

#: glance/common/swift_store_utils.py:101
msgid "Invalid format of swift store config cfg"
msgstr ""

#: glance/common/utils.py:115
#, python-format
msgid "Error: cooperative_iter exception %s"
msgstr "Erreur : exception cooperative_iter %s"

#: glance/common/utils.py:514
msgid ""
"Error setting up the debug environment. Verify that the option "
"pydev_worker_debug_host is pointing to a valid hostname or IP on which a "
"pydev server is listening on the port indicated by pydev_worker_debug_port."
msgstr ""

#: glance/common/wsgi.py:332
#, python-format
msgid "Not respawning child %d, cannot recover from termination"
msgstr "Aucune relance de l'enfant %d, récupération impossible après arrêt"

#: glance/common/artifacts/loader.py:96
#, python-format
msgid "Unable to load artifacts: %s"
msgstr ""

#: glance/common/artifacts/loader.py:164
#, python-format
msgid "Could not load plugin from %(module)s: %(msg)s"
msgstr ""

#: glance/common/location_strategy/__init__.py:66
#, python-format
msgid "Failed to load location strategy module %(module)s: %(e)s"
msgstr ""

#: glance/common/scripts/__init__.py:40
#, python-format
msgid ""
"This task type %(task_type)s is not supported by the current deployment of "
"Glance. Please refer the documentation provided by OpenStack or your "
"operator for more information."
msgstr ""

#: glance/common/scripts/__init__.py:50
#, python-format
msgid "Failed to save task %(task_id)s in DB as task_repo is %(task_repo)s"
msgstr ""

#: glance/common/scripts/utils.py:48
#, python-format
msgid "Task not found for task_id %s"
msgstr "Tache non trouvé pour  task_id %s"

#: glance/db/sqlalchemy/artifacts.py:346
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "Direction d'ordonnancement inconnue, choisir 'desc' ou 'asc'"

#: glance/db/sqlalchemy/artifacts.py:532
msgid "Cannot use this parameter with the operator IN"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:539
#, python-format
msgid "Operator %s is not supported"
msgstr ""

#: glance/db/sqlalchemy/metadata.py:185
#, python-format
msgid "Json schema files not found in %s. Aborting."
msgstr "Fichier du schéma Json non trouvé dans %s. Abandon."

#: glance/db/sqlalchemy/metadata.py:451
msgid ""
"To use --prefer_new or --overwrite you need to combine of these options with "
"--merge option."
msgstr ""

#: glance/db/sqlalchemy/metadata.py:456
msgid ""
"Please provide no more than one option from this list: --prefer_new, --"
"overwrite"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:63
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:97
#, python-format
msgid "Invalid store uri for image: %(image_id)s. Details: %(reason)s"
msgstr "uri magasin non valide pour image: %(image_id)s. Details: %(reason)s"

#: glance/domain/__init__.py:413
#, python-format
msgid ""
"Task [%(task_id)s] status failed to change from %(cur_status)s to "
"%(new_status)s"
msgstr ""

#: glance/domain/__init__.py:521
#, python-format
msgid "Failed to load the %s executor provided in the config."
msgstr ""

#: glance/image_cache/__init__.py:271
#, python-format
msgid ""
"Exception encountered while tee'ing image '%(image_id)s' into cache: "
"%(error)s. Continuing with response."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:398
#, python-format
msgid "Error executing SQLite call. Got error: %s"
msgstr "Erreur lors de l'exécution de l'appel SQLite. Erreur obtenue : %s"

#: glance/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "Fixe la durée de l'appel de la boucle"

#: glance/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "dans l'appel en boucle dynamique"

#: glance/openstack/common/service.py:264
msgid "Unhandled exception"
msgstr "Exception non prise en charge"

#: glance/registry/api/v1/images.py:136
msgid "Unable to get images"
msgstr "Impossible d'obtenir les images."

#: glance/registry/api/v1/images.py:354
#, python-format
msgid "Unable to show image %s"
msgstr "Impossible d'afficher l'image %s"

#: glance/registry/api/v1/images.py:390
#, python-format
msgid "Unable to delete image %s"
msgstr "Impossible de supprimer l'image %s"

#: glance/registry/api/v1/images.py:442
#, python-format
msgid "Unable to create image %s"
msgstr "Impossible de créer l'image %s"

#: glance/registry/api/v1/images.py:515
#, python-format
msgid "Unable to update image %s"
msgstr "Impossible de mettre à jour l'image %s"

#: glance/registry/client/v1/client.py:129
#, python-format
msgid "Registry client request %(method)s %(action)s raised %(exc_name)s"
msgstr "Demande client de registre %(method)s %(action)s produite %(exc_name)s"

#: glance/search/api/v0_1/search.py:243
#, python-format
msgid "Failed to retrieve RBAC filters from search plugin %(ext)s: %(e)s"
msgstr ""

#: glance/tests/functional/v2/test_metadef_resourcetypes.py:99
#, python-format
msgid "Forbidden to create resource type. Reason: %(reason)s"
msgstr "Creation du type de ressource refuse. Raison: %(reason)s "
