# Translations template for glance.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the glance project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: glance 2015.1.dev42\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-04-03 06:02+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: glance/scrubber.py:218
#, python-format
msgid "Failed to find image to delete: %s"
msgstr ""

#: glance/scrubber.py:258
#, python-format
msgid "%s directory does not exist."
msgstr ""

#: glance/scrubber.py:583
#, python-format
msgid "Unable to delete URI from image %s."
msgstr ""

#: glance/api/common.py:171
#, python-format
msgid ""
"User %(user)s attempted to upload an image of unknown size that will "
"exceed the quota. %(remaining)d bytes remaining."
msgstr ""

#: glance/api/common.py:180
#, python-format
msgid ""
"User %(user)s attempted to upload an image of size %(size)d that will "
"exceed the quota. %(remaining)d bytes remaining."
msgstr ""

#: glance/api/middleware/version_negotiation.py:67
msgid "Unknown version. Returning version choices."
msgstr ""

#: glance/api/v1/images.py:704
#, python-format
msgid ""
"Failed to activate image %s in registry. About to delete image bits from "
"store and update status to 'killed'."
msgstr ""

#: glance/api/v2/images.py:945
#, python-format
msgid ""
"Could not find schema properties file %s. Continuing without custom "
"properties"
msgstr ""

#: glance/api/v2/tasks.py:72
#, python-format
msgid "Forbidden to create task. Reason: %(reason)s"
msgstr ""

#: glance/api/v2/tasks.py:110
#, python-format
msgid "Failed to find task %(task_id)s. Reason: %(reason)s"
msgstr ""

#: glance/api/v2/tasks.py:115
#, python-format
msgid "Forbidden to get task %(task_id)s. Reason: %(reason)s"
msgstr ""

#: glance/async/utils.py:62
#, python-format
msgid "An optional task has failed, the failure was: %s"
msgstr ""

#: glance/async/flows/convert.py:67
#, python-format
msgid ""
"The conversion format is None, please add a value for it in the config "
"file for this task to work: %s"
msgstr ""

#: glance/cmd/replicator.py:607
#, python-format
msgid ""
"%(image_id)s: field %(key)s differs (source is %(master_value)s, "
"destination is %(slave_value)s)"
msgstr ""

#: glance/cmd/replicator.py:620
#, python-format
msgid "Image %s entirely missing from the destination"
msgstr ""

#: glance/common/store_utils.py:65
#, python-format
msgid "Failed to delete image %s in store from URI"
msgstr ""

#: glance/common/wsgi.py:326
#, python-format
msgid "Unrecognised child %s"
msgstr ""

#: glance/common/artifacts/loader.py:125
#, python-format
msgid "Can't load artifact %s: load disabled in config"
msgstr ""

#: glance/common/artifacts/loader.py:151
#, python-format
msgid "Can't load artifact %s: not in available_plugins list"
msgstr ""

#: glance/common/scripts/image_import/main.py:158
#, python-format
msgid "Task %(task_id)s failed with exception %(error)s"
msgstr ""

#: glance/db/simple/api.py:387
#, python-format
msgid "Could not find image %s"
msgstr ""

#: glance/db/simple/api.py:392
msgid "Unable to get deleted image"
msgstr ""

#: glance/db/simple/api.py:396
msgid "Unable to get unowned image"
msgstr ""

#: glance/db/simple/api.py:909
#, python-format
msgid "Could not find task %s"
msgstr ""

#: glance/db/simple/api.py:914
#, python-format
msgid "Unable to get deleted task %s"
msgstr ""

#: glance/db/simple/api.py:1075
#, python-format
msgid "Could not find task info %s"
msgstr ""

#: glance/db/sqlalchemy/api.py:77
msgid "Deadlock detected. Retrying..."
msgstr ""

#: glance/db/sqlalchemy/api.py:117
msgid "Attempted to modify image user did not own."
msgstr ""

#: glance/db/sqlalchemy/api.py:332
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:135
msgid "Artifact with the specified type, name and version already exists"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:240
#, python-format
msgid "Artifact with id=%s not found"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:243
#, python-format
msgid "Artifact with id=%s is not accessible"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:423
#, python-format
msgid "Show level %s is not supported in this operation"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:655
#, python-format
msgid ""
"Artifact with the specified type, name and versions already has the "
"direct dependency=%s"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:685
#, python-format
msgid ""
"Artifact with the specified type, name and version already has the direct"
" dependency=%d"
msgstr ""

#: glance/db/sqlalchemy/metadata.py:340 glance/db/sqlalchemy/metadata.py:348
#: glance/db/sqlalchemy/metadata.py:357
#, python-format
msgid "Duplicate entry for values: %s"
msgstr ""

#: glance/db/sqlalchemy/metadef_api/tag.py:37
#, python-format
msgid "Metadata tag not found for id %s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:92
#, python-format
msgid "Failed to decrypt location value for image %(image_id)s"
msgstr ""

#: glance/domain/__init__.py:505
msgid "The `eventlet` executor has been deprecated. Use `taskflow` instead."
msgstr ""

#: glance/image_cache/__init__.py:74
#, python-format
msgid ""
"Image cache driver '%(driver_name)s' failed to load. Got error: "
"'%(import_err)s."
msgstr ""

#: glance/image_cache/__init__.py:95
#, python-format
msgid ""
"Image cache driver '%(driver_module)s' failed to configure. Got error: "
"'%(config_err)s"
msgstr ""

#: glance/image_cache/prefetcher.py:48
#, python-format
msgid "Image '%s' is not active. Not caching."
msgstr ""

#: glance/image_cache/prefetcher.py:53
#, python-format
msgid "No metadata found for image '%s'"
msgstr ""

#: glance/image_cache/prefetcher.py:81
msgid "Failed to successfully cache all images in queue."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:333
#, python-format
msgid ""
"Fetch of cache file failed (%(e)s), rolling back by moving "
"'%(incomplete_path)s' to '%(invalid_path)s'"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:459
#, python-format
msgid "Failed to delete file %(path)s. Got error: %(e)s"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:496
#: glance/image_cache/drivers/xattr.py:447
#, python-format
msgid "Cached image file '%s' doesn't exist, unable to delete"
msgstr ""

#: glance/openstack/common/loopingcall.py:87
#, python-format
msgid "task %(func_name)r run outlasted interval by %(delay).2f sec"
msgstr ""

#: glance/openstack/common/service.py:351
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: glance/registry/api/v1/images.py:126
#, python-format
msgid "Invalid marker. Image %(id)s could not be found."
msgstr ""

#: glance/registry/api/v1/images.py:131 glance/registry/api/v1/members.py:76
#: glance/registry/api/v1/members.py:111 glance/registry/api/v1/members.py:229
#: glance/registry/api/v1/members.py:293
#, python-format
msgid "Access denied to image %(id)s but returning 'not found'"
msgstr ""

#: glance/registry/api/v1/members.py:118 glance/registry/api/v1/members.py:236
#: glance/registry/api/v1/members.py:300
#, python-format
msgid "User lacks permission to share image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:129 glance/registry/api/v1/members.py:146
#: glance/registry/api/v1/members.py:249
#, python-format
msgid "Invalid membership association specified for image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:339
#, python-format
msgid "Member %(id)s not found"
msgstr ""

